config/routes.rb
Rails.application.routes.draw do

  root 'games#index'

  resources :games do
    collection do
      post "onemore"
      post "stay"
      post "split"
      post "doublebet"
      get "reset_player"
    end
  end

end

app/models/card.rb
class Card
	@@suits = [:diams,:clubs,:hearts,:spades]
	@@symbols = [2,3,4,5,6,7,8,9,10,:J,:Q,:K,:A]

	attr_reader :symbol, :suit

	def initialize(symbol, suit)
	    if @@symbols.include?(symbol) and @@suits.include?(suit)
	      @symbol = symbol
	      @suit = suit
	    else
	      raise "Wrong card type"
	    end
	end

	def self.suits
       	@@suits
	end

	def self.symbols
		@@symbols
	end

	def value
		value = nil
		if @symbol.is_a? Integer
			value = @symbol
		else
			value = 10
			if @symbol == :A
				value = 11
			end
		end
		value
	end

end

app/models/deck.rb
class Deck
	attr_reader :cards

	def initialize
		@cards = []
		Card.suits.each do |suit|
			Card.symbols.each do |symbol|
				@cards.push Card.new(symbol, suit)
			end
		end
		@random_card = 26 + rand(10) # random card from second part of a deck to reshuffle Deck
		@cards.shuffle!
	end

	def need_reshuffle
		@cards.count < (52 - @random_card) 
	end

	def next
		raise "Deck is empty" if @cards.count == 0
        @cards.pop
	end
end

app/models/game.rb
class Game
	attr_reader :bet, :dealer, :hands, :finished
	def initialize(bet, deck)
		@finished = false
		@bet = bet
		@deck = deck
		@dealer = Hand.new(bet)
		@dealer.take deck.next
		@dealer.take deck.next
		hand = Hand.new(bet)
		hand.take deck.next
		hand.take deck.next
		@hands = [hand]
		@prizes_taken = false
	end

	def take_card(hand = 0)
		return false if @hands[hand].nil? || !@hands[hand].canplay
		@hands[hand].take @deck.next
		@hands[hand].check_busting
		finish?
	end

	def stay(hand = 0)
		return false if @hands[hand].nil? || !@hands[hand].canplay		
		@hands[hand].stay
		finish?
	end

	def doublebet(hand = 0)
		return false if @hands[hand].nil? || !@hands[hand].canplay
		@hands[hand].doublebet
		@hands[hand].take @deck.next
		@hands[hand].stay
		finish?
	end

	def split(hand = 0)
		return false if @hands[hand].nil? || !@hands[hand].canplay
		temp = @hands[hand]
		@hands.delete_at(hand)
		hand = Hand.new(temp.bet)
		hand.take temp.cards.first
		hand.take @deck.next
		@hands.push hand
		hand = Hand.new(temp.bet)
		hand.take temp.cards.last
		hand.take @deck.next
		@hands.push hand
	end

	def dealer_take_cards
		until @dealer.busted? || @dealer.max_value >=17 do
			@dealer.take @deck.next
		end
	end

	def prizes
		prizes = 0
		@hands.each do |hand|
			if hand.status == :stand
				if @dealer.busted?
					prizes += hand.bet * 2
				else
					if hand.max_value > @dealer.max_value
						prizes += hand.bet * 2
					end
				end
			end
		end
		prizes
	end

	def take_prizes
		return 0 if @prizes_taken		
		@prizes_taken = true
		prizes
	end

	def finish?
		@finished = true if @hands.map(&:status).index(:ingame).nil?
		dealer_take_cards if !@hands.map(&:status).index(:stand).nil?
	end

end

app/models/hand.rb
class Hand
	attr_reader :status, :cards, :bet

	def initialize(bet)
		@bet = bet
		@status = :ingame
		@cards = []
	end

	def take(card)
		@cards.push(card)
		check_busting
	end

	def doublebet
		@bet += @bet
	end

	def stay
		@status = :stand if canplay
	end

	def canplay
		@status == :ingame
	end

	def check_busting
		@status = :busted if calc_value.select{|cards_sum| cards_sum <= 21}.count == 0
	end

	def cansplit?
		@cards.count == 2 and @cards.first.symbol == @cards.last.symbol and canplay
	end

	def busted?
		status == :busted
	end

	def max_value
		calc_value.select{|cards_sum| cards_sum <= 21}.max
	end

	def calc_value
		variants = []
		values = @cards.map(&:value)
		variants.push values.sum
		aces = values.select{|v| v == 11}.count
		aces.times do |i| 
		  variants.push values.sum - 10*(i+1)
		end
		variants
	end
end

app/models/player.rb
class Player
	attr_reader :deck, :money, :hands, :game
	def initialize
		@money = 1000
		@deck = Deck.new
	end

	def new_game(bet)
		return false if @money < bet || bet <= 0
		@money -= bet
		#@deck = Deck.new if @deck.need_reshuffle
		@game = Game.new(bet, @deck)
	end

	def split(hand_index)
		hand = @game.hands[hand_index]
		return false if !cansplit?(hand)
		@money -= hand.bet
		@game.split(hand_index)
	end

	def doublebet(hand_index)
		hand = @game.hands[hand_index]
		return false if !candoublebet?(hand)
		@money -= hand.bet
		@game.doublebet(hand_index)
	end

	def cansplit?(hand)
		!hand.nil? && @money >= hand.bet && hand.canplay && hand.cansplit?
	end

	def candoublebet?(hand)
		!hand.nil? && @money >= hand.bet && hand.canplay
	end


	def stay(hand_index)
		@game.stay(hand_index)
		finish_game
	end

	def take_card(hand_index)
		@game.take_card(hand_index)
		finish_game
	end

	def finish_game
	   @money += @game.take_prizes if @game.finished
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  around_filter :handle_error

  def index

  end

  def handle_error
    begin
      yield             
    rescue Exception => e  
      render :error, locals: {error: e}            
    end
  end 
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_filter :restore_player
  after_filter :store_player

  def index

  end

  def new
  	@player.new_game(params[:bet].to_i)
  	redirect_to :root
  end

  def doublebet
  	@player.doublebet(params[:index].to_i)
  	redirect_to :root
  end

  def split
  	@player.split(params[:index].to_i)
  	redirect_to :root
  end

  def stay
  	@player.stay(params[:index].to_i)
  	redirect_to :root
  end

  def onemore
  	@player.take_card(params[:index].to_i)
  	redirect_to :root
  end

  def reset_player
  	@player = Player.new
  	redirect_to :root
  end


  def restore_player  	
  	if session[:player]
  		begin
  			@player = Marshal::load(session[:player])
  		rescue
  			@player = Player.new
  		end
  	else
  		@player = Player.new
  	end
  end

  def store_player
  	session[:player] = Marshal::dump(@player)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_actions.html.slim
.btn-group
	= link_to "One more", onemore_games_path(index: index), method: :post, class: "btn btn-primary"
	= link_to "Doublebet", doublebet_games_path(index: index), method: :post, class: "btn btn-primary"
	= link_to "Stay", stay_games_path(index: index), method: :post, class: "btn btn-primary"
	= link_to "Split", split_games_path(index: index), method: :post, class: "btn btn-primary" if @player.cansplit?(hand)

app/views/games/error.html.slim
| Error: #{error.message} 
= link_to "Reset player", reset_player_games_path

app/views/games/index.html.slim
div
  | You have #{@player.money} coins



-if @player.game
  -if @player.game.finished
    -if @player.game.prizes > 0
      div
        | You win #{@player.game.prizes} coins

    div
      | Dealer: 
      - @player.game.dealer.cards.each do |card|
       |  #{card.symbol}&#{card.suit}; 
  -else
    div
      | Dealer: #{@player.game.dealer.cards.first.symbol}&#{@player.game.dealer.cards.first.suit}; ?
  div
    | You: 
    - @player.game.hands.each_with_index do |hand, index|
    	br
    	| (bet #{hand.bet} coins) 
    	- hand.cards.each do |card|
     		| #{card.symbol}&#{card.suit}; 
     	- if hand.busted?
     	  b
     	    | busted
     	div = render partial: "actions", locals: {hand: hand, index: index }  if hand.canplay


- if !@player.game || @player.game.finished
	= form_tag(new_game_path, method: "get") do
	  = label_tag(:bet, "Bet:")
	  = text_field_tag(:bet) 
	  = submit_tag("New game")
	= link_to "Reset player", reset_player_games_path
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>